name: "Test Run"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1
    - name: Run the Action
      uses: ./
      with:
        username: matootie
        personalAccessToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
